// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type HomeDocumentDataSlicesSlice =
    | TitleDescImgBtnSlice
    | ServicesSlice
    | PropertiesSlice
    | TitleDescBtnSlice

/**
 * Content for Home documents
 */
interface HomeDocumentData {
    /**
     * Slice Zone field in *Home*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: home.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
    /**
     * Meta Description field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: home.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_description: prismic.KeyTextField

    /**
     * Meta Image field in *Home*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>

    /**
     * Meta Title field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: home.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, 'home', Lang>

type ServicesDocumentDataSlicesSlice = ServicesSlice

/**
 * Content for Services documents
 */
interface ServicesDocumentData {
    /**
     * Slice Zone field in *Services*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: services.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<ServicesDocumentDataSlicesSlice>
    /**
     * Meta Description field in *Services*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: services.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_description: prismic.KeyTextField

    /**
     * Meta Image field in *Services*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: services.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>

    /**
     * Meta Title field in *Services*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: services.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField
}

/**
 * Services document from Prismic
 *
 * - **API ID**: `services`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithUID<
        Simplify<ServicesDocumentData>,
        'services',
        Lang
    >

export type AllDocumentTypes = HomeDocument | ServicesDocument

/**
 * Primary content in *Properties → Items*
 */
export interface PropertiesSliceDefaultItem {
    /**
     * img field in *Properties → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: properties.items[].img
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    img: prismic.ImageField<never>

    /**
     * title field in *Properties → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: properties.items[].title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * desc field in *Properties → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: properties.items[].desc
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    desc: prismic.KeyTextField
}

/**
 * Default variation for Properties Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PropertiesSliceDefault = prismic.SharedSliceVariation<
    'default',
    Record<string, never>,
    Simplify<PropertiesSliceDefaultItem>
>

/**
 * Slice variation for *Properties*
 */
type PropertiesSliceVariation = PropertiesSliceDefault

/**
 * Properties Shared Slice
 *
 * - **API ID**: `properties`
 * - **Description**: Properties
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PropertiesSlice = prismic.SharedSlice<
    'properties',
    PropertiesSliceVariation
>

/**
 * Primary content in *Services → Items*
 */
export interface ServicesSliceDefaultItem {
    /**
     * img field in *Services → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: services.items[].img
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    img: prismic.ImageField<never>

    /**
     * title field in *Services → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: services.items[].title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * desc field in *Services → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: services.items[].desc
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    desc: prismic.KeyTextField

    /**
     * slug field in *Services → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: services.items[].slug
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    slug: prismic.KeyTextField
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<
    'default',
    Record<string, never>,
    Simplify<ServicesSliceDefaultItem>
>

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSlice = prismic.SharedSlice<
    'services',
    ServicesSliceVariation
>

/**
 * Primary content in *GetInTouch → Primary*
 */
export interface TitleDescBtnSliceDefaultPrimary {
    /**
     * title field in *GetInTouch → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_desc_btn.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * desc field in *GetInTouch → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_desc_btn.primary.desc
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    desc: prismic.KeyTextField

    /**
     * buttonText field in *GetInTouch → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_desc_btn.primary.buttontext
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    buttontext: prismic.KeyTextField

    /**
     * buttonValue field in *GetInTouch → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_desc_btn.primary.buttonvalue
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    buttonvalue: prismic.KeyTextField
}

/**
 * Default variation for GetInTouch Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleDescBtnSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<TitleDescBtnSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *GetInTouch*
 */
type TitleDescBtnSliceVariation = TitleDescBtnSliceDefault

/**
 * GetInTouch Shared Slice
 *
 * - **API ID**: `title_desc_btn`
 * - **Description**: TitleDescBtn
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleDescBtnSlice = prismic.SharedSlice<
    'title_desc_btn',
    TitleDescBtnSliceVariation
>

/**
 * Primary content in *HomeHero → Primary*
 */
export interface TitleDescImgBtnSliceDefaultPrimary {
    /**
     * title field in *HomeHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_desc_img_btn.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * desc field in *HomeHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_desc_img_btn.primary.desc
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    desc: prismic.KeyTextField

    /**
     * img field in *HomeHero → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: title_desc_img_btn.primary.img
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    img: prismic.ImageField<never>

    /**
     * buttonText field in *HomeHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_desc_img_btn.primary.buttontext
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    buttontext: prismic.KeyTextField

    /**
     * buttonValue field in *HomeHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_desc_img_btn.primary.buttonvalue
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    buttonvalue: prismic.KeyTextField
}

/**
 * Default variation for HomeHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleDescImgBtnSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<TitleDescImgBtnSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *HomeHero*
 */
type TitleDescImgBtnSliceVariation = TitleDescImgBtnSliceDefault

/**
 * HomeHero Shared Slice
 *
 * - **API ID**: `title_desc_img_btn`
 * - **Description**: TitleDescImgBtn
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleDescImgBtnSlice = prismic.SharedSlice<
    'title_desc_img_btn',
    TitleDescImgBtnSliceVariation
>

declare module '@prismicio/client' {
    interface CreateClient {
        (
            repositoryNameOrEndpoint: string,
            options?: prismic.ClientConfig
        ): prismic.Client<AllDocumentTypes>
    }

    namespace Content {
        export type {
            HomeDocument,
            HomeDocumentData,
            HomeDocumentDataSlicesSlice,
            ServicesDocument,
            ServicesDocumentData,
            ServicesDocumentDataSlicesSlice,
            AllDocumentTypes,
            PropertiesSlice,
            PropertiesSliceVariation,
            PropertiesSliceDefault,
            ServicesSlice,
            ServicesSliceVariation,
            ServicesSliceDefault,
            TitleDescBtnSlice,
            TitleDescBtnSliceVariation,
            TitleDescBtnSliceDefault,
            TitleDescImgBtnSlice,
            TitleDescImgBtnSliceVariation,
            TitleDescImgBtnSliceDefault,
        }
    }
}
