// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type AboutDocumentDataSlicesSlice =
    | AboutHeroSlice
    | AboutTalentSlice
    | LocationsSlice
    | TitleDescBtnSlice

/**
 * Content for About documents
 */
interface AboutDocumentData {
    /**
     * Slice Zone field in *About*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: about.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<AboutDocumentDataSlicesSlice>
    /**
     * Meta Description field in *About*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: about.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_description: prismic.KeyTextField

    /**
     * Meta Image field in *About*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: about.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>

    /**
     * Meta Title field in *About*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: about.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithoutUID<
        Simplify<AboutDocumentData>,
        'about',
        Lang
    >

type ContactDocumentDataSlicesSlice = ContactHeroSlice | LocationsSlice

/**
 * Content for Contact documents
 */
interface ContactDocumentData {
    /**
     * Slice Zone field in *Contact*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: contact.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<ContactDocumentDataSlicesSlice>
    /**
     * Meta Description field in *Contact*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: contact.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_description: prismic.KeyTextField

    /**
     * Meta Image field in *Contact*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: contact.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>

    /**
     * Meta Title field in *Contact*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: contact.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField
}

/**
 * Contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithoutUID<
        Simplify<ContactDocumentData>,
        'contact',
        Lang
    >

type HomeDocumentDataSlicesSlice =
    | TitleDescImgBtnSlice
    | ServicesSlice
    | PropertiesSlice
    | TitleDescBtnSlice

/**
 * Content for Home documents
 */
interface HomeDocumentData {
    /**
     * Slice Zone field in *Home*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: home.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
    /**
     * Meta Description field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: home.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_description: prismic.KeyTextField

    /**
     * Meta Image field in *Home*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: home.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>

    /**
     * Meta Title field in *Home*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: home.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, 'home', Lang>

type LocDocumentDataSlicesSlice = LocItemSlice | TitleDescBtnSlice

/**
 * Content for Location documents
 */
interface LocDocumentData {
    /**
     * Slice Zone field in *Location*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: loc.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<LocDocumentDataSlicesSlice>
    /**
     * Meta Description field in *Location*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: loc.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_description: prismic.KeyTextField

    /**
     * Meta Image field in *Location*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: loc.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>

    /**
     * Meta Title field in *Location*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: loc.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField
}

/**
 * Location document from Prismic
 *
 * - **API ID**: `loc`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LocDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithoutUID<Simplify<LocDocumentData>, 'loc', Lang>

/**
 * Item in *Navigation → navLinks*
 */
export interface NavigationDocumentDataNavlinksItem {
    /**
     * text field in *Navigation → navLinks*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.navlinks[].text
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    text: prismic.KeyTextField

    /**
     * value field in *Navigation → navLinks*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.navlinks[].value
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    value: prismic.KeyTextField
}

/**
 * Item in *Navigation → footerLocations*
 */
export interface NavigationDocumentDataFooterlocationsItem {
    /**
     * text field in *Navigation → footerLocations*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.footerlocations[].text
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    text: prismic.RichTextField
}

/**
 * Item in *Navigation → footerContacts*
 */
export interface NavigationDocumentDataFootercontactsItem {
    /**
     * text field in *Navigation → footerContacts*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.footercontacts[].text
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    text: prismic.RichTextField
}

/**
 * Item in *Navigation → footerSocials*
 */
export interface NavigationDocumentDataFootersocialsItem {
    /**
     * img field in *Navigation → footerSocials*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.footersocials[].img
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    img: prismic.ImageField<never>
}

type NavigationDocumentDataSlicesSlice = never

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
    /**
     * headerLogo field in *Navigation*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.headerlogo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    headerlogo: prismic.ImageField<never>

    /**
     * navLinks field in *Navigation*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.navlinks[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    navlinks: prismic.GroupField<Simplify<NavigationDocumentDataNavlinksItem>>

    /**
     * footerLogo field in *Navigation*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.footerlogo
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    footerlogo: prismic.ImageField<never>

    /**
     * footerLocations field in *Navigation*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.footerlocations[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    footerlocations: prismic.GroupField<
        Simplify<NavigationDocumentDataFooterlocationsItem>
    >

    /**
     * footerContacts field in *Navigation*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.footercontacts[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    footercontacts: prismic.GroupField<
        Simplify<NavigationDocumentDataFootercontactsItem>
    >

    /**
     * footerSocials field in *Navigation*
     *
     * - **Field Type**: Group
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.footersocials[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#group
     */
    footersocials: prismic.GroupField<
        Simplify<NavigationDocumentDataFootersocialsItem>
    >

    /**
     * Slice Zone field in *Navigation*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<NavigationDocumentDataSlicesSlice>
    /**
     * Meta Description field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: navigation.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_description: prismic.KeyTextField

    /**
     * Meta Image field in *Navigation*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: navigation.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>

    /**
     * Meta Title field in *Navigation*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: navigation.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithoutUID<
        Simplify<NavigationDocumentData>,
        'navigation',
        Lang
    >

type ServicesDocumentDataSlicesSlice =
    | ServicesSlice
    | ServiceHeroSlice
    | ServiceProjectsSlice
    | TitleDescBtnSlice

/**
 * Content for Services documents
 */
interface ServicesDocumentData {
    /**
     * Slice Zone field in *Services*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: services.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/field#slices
     */
    slices: prismic.SliceZone<ServicesDocumentDataSlicesSlice>
    /**
     * Meta Description field in *Services*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A brief summary of the page
     * - **API ID Path**: services.meta_description
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_description: prismic.KeyTextField

    /**
     * Meta Image field in *Services*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: services.meta_image
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    meta_image: prismic.ImageField<never>

    /**
     * Meta Title field in *Services*
     *
     * - **Field Type**: Text
     * - **Placeholder**: A title of the page used for social media and search engines
     * - **API ID Path**: services.meta_title
     * - **Tab**: SEO & Metadata
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    meta_title: prismic.KeyTextField
}

/**
 * Services document from Prismic
 *
 * - **API ID**: `services`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServicesDocument<Lang extends string = string> =
    prismic.PrismicDocumentWithUID<
        Simplify<ServicesDocumentData>,
        'services',
        Lang
    >

export type AllDocumentTypes =
    | AboutDocument
    | ContactDocument
    | HomeDocument
    | LocDocument
    | NavigationDocument
    | ServicesDocument

/**
 * Primary content in *AboutHero → Primary*
 */
export interface AboutHeroSliceDefaultPrimary {
    /**
     * title field in *AboutHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about_hero.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * desc field in *AboutHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about_hero.primary.desc
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    desc: prismic.KeyTextField

    /**
     * img field in *AboutHero → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: about_hero.primary.img
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    img: prismic.ImageField<never>
}

/**
 * Default variation for AboutHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutHeroSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<AboutHeroSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *AboutHero*
 */
type AboutHeroSliceVariation = AboutHeroSliceDefault

/**
 * AboutHero Shared Slice
 *
 * - **API ID**: `about_hero`
 * - **Description**: AboutHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutHeroSlice = prismic.SharedSlice<
    'about_hero',
    AboutHeroSliceVariation
>

/**
 * Primary content in *AboutTalent → Primary*
 */
export interface AboutTalentSliceDefaultPrimary {
    /**
     * title field in *AboutTalent → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about_talent.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * desc field in *AboutTalent → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: about_talent.primary.desc
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    desc: prismic.KeyTextField

    /**
     * img field in *AboutTalent → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: about_talent.primary.img
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    img: prismic.ImageField<never>

    /**
     * imgLeft field in *AboutTalent → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: about_talent.primary.imgleft
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    imgleft: prismic.BooleanField
}

/**
 * Default variation for AboutTalent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutTalentSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<AboutTalentSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *AboutTalent*
 */
type AboutTalentSliceVariation = AboutTalentSliceDefault

/**
 * AboutTalent Shared Slice
 *
 * - **API ID**: `about_talent`
 * - **Description**: AboutTalent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutTalentSlice = prismic.SharedSlice<
    'about_talent',
    AboutTalentSliceVariation
>

/**
 * Primary content in *ContactHero → Primary*
 */
export interface ContactHeroSliceDefaultPrimary {
    /**
     * title field in *ContactHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_hero.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * desc field in *ContactHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: contact_hero.primary.desc
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    desc: prismic.KeyTextField
}

/**
 * Default variation for ContactHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactHeroSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<ContactHeroSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *ContactHero*
 */
type ContactHeroSliceVariation = ContactHeroSliceDefault

/**
 * ContactHero Shared Slice
 *
 * - **API ID**: `contact_hero`
 * - **Description**: ContactHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactHeroSlice = prismic.SharedSlice<
    'contact_hero',
    ContactHeroSliceVariation
>

/**
 * Primary content in *LocItem → Primary*
 */
export interface LocItemSliceDefaultPrimary {
    /**
     * img field in *LocItem → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: loc_item.primary.img
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    img: prismic.ImageField<never>

    /**
     * title field in *LocItem → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: loc_item.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * imgLeft field in *LocItem → Primary*
     *
     * - **Field Type**: Boolean
     * - **Placeholder**: *None*
     * - **Default Value**: false
     * - **API ID Path**: loc_item.primary.imgleft
     * - **Documentation**: https://prismic.io/docs/field#boolean
     */
    imgleft: prismic.BooleanField
}

/**
 * Primary content in *LocItem → Items*
 */
export interface LocItemSliceDefaultItem {
    /**
     * address field in *LocItem → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: loc_item.items[].address
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    address: prismic.RichTextField

    /**
     * contact field in *LocItem → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: loc_item.items[].contact
     * - **Documentation**: https://prismic.io/docs/field#rich-text-title
     */
    contact: prismic.RichTextField
}

/**
 * Default variation for LocItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LocItemSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<LocItemSliceDefaultPrimary>,
    Simplify<LocItemSliceDefaultItem>
>

/**
 * Slice variation for *LocItem*
 */
type LocItemSliceVariation = LocItemSliceDefault

/**
 * LocItem Shared Slice
 *
 * - **API ID**: `loc_item`
 * - **Description**: LocItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LocItemSlice = prismic.SharedSlice<
    'loc_item',
    LocItemSliceVariation
>

/**
 * Primary content in *Locations → Items*
 */
export interface LocationsSliceDefaultItem {
    /**
     * img field in *Locations → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: locations.items[].img
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    img: prismic.ImageField<never>

    /**
     * title field in *Locations → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: locations.items[].title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * buttonText field in *Locations → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: locations.items[].buttontext
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    buttontext: prismic.KeyTextField

    /**
     * buttonValue field in *Locations → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: locations.items[].buttonvalue
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    buttonvalue: prismic.KeyTextField
}

/**
 * Default variation for Locations Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LocationsSliceDefault = prismic.SharedSliceVariation<
    'default',
    Record<string, never>,
    Simplify<LocationsSliceDefaultItem>
>

/**
 * Slice variation for *Locations*
 */
type LocationsSliceVariation = LocationsSliceDefault

/**
 * Locations Shared Slice
 *
 * - **API ID**: `locations`
 * - **Description**: Locations
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LocationsSlice = prismic.SharedSlice<
    'locations',
    LocationsSliceVariation
>

/**
 * Primary content in *Properties → Items*
 */
export interface PropertiesSliceDefaultItem {
    /**
     * img field in *Properties → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: properties.items[].img
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    img: prismic.ImageField<never>

    /**
     * title field in *Properties → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: properties.items[].title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * desc field in *Properties → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: properties.items[].desc
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    desc: prismic.KeyTextField
}

/**
 * Default variation for Properties Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PropertiesSliceDefault = prismic.SharedSliceVariation<
    'default',
    Record<string, never>,
    Simplify<PropertiesSliceDefaultItem>
>

/**
 * Slice variation for *Properties*
 */
type PropertiesSliceVariation = PropertiesSliceDefault

/**
 * Properties Shared Slice
 *
 * - **API ID**: `properties`
 * - **Description**: Properties
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PropertiesSlice = prismic.SharedSlice<
    'properties',
    PropertiesSliceVariation
>

/**
 * Primary content in *ServiceHero → Primary*
 */
export interface ServiceHeroSliceDefaultPrimary {
    /**
     * title field in *ServiceHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: service_hero.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * desc field in *ServiceHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: service_hero.primary.desc
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    desc: prismic.KeyTextField
}

/**
 * Default variation for ServiceHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceHeroSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<ServiceHeroSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *ServiceHero*
 */
type ServiceHeroSliceVariation = ServiceHeroSliceDefault

/**
 * ServiceHero Shared Slice
 *
 * - **API ID**: `service_hero`
 * - **Description**: ServiceHero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceHeroSlice = prismic.SharedSlice<
    'service_hero',
    ServiceHeroSliceVariation
>

/**
 * Primary content in *ServiceProjects → Items*
 */
export interface ServiceProjectsSliceDefaultItem {
    /**
     * img field in *ServiceProjects → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: service_projects.items[].img
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    img: prismic.ImageField<never>

    /**
     * title field in *ServiceProjects → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: service_projects.items[].title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * desc field in *ServiceProjects → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: service_projects.items[].desc
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    desc: prismic.KeyTextField
}

/**
 * Default variation for ServiceProjects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceProjectsSliceDefault = prismic.SharedSliceVariation<
    'default',
    Record<string, never>,
    Simplify<ServiceProjectsSliceDefaultItem>
>

/**
 * Slice variation for *ServiceProjects*
 */
type ServiceProjectsSliceVariation = ServiceProjectsSliceDefault

/**
 * ServiceProjects Shared Slice
 *
 * - **API ID**: `service_projects`
 * - **Description**: ServiceProjects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceProjectsSlice = prismic.SharedSlice<
    'service_projects',
    ServiceProjectsSliceVariation
>

/**
 * Primary content in *Services → Items*
 */
export interface ServicesSliceDefaultItem {
    /**
     * img field in *Services → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: services.items[].img
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    img: prismic.ImageField<never>

    /**
     * title field in *Services → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: services.items[].title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * desc field in *Services → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: services.items[].desc
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    desc: prismic.KeyTextField

    /**
     * slug field in *Services → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: services.items[].slug
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    slug: prismic.KeyTextField
}

/**
 * Default variation for Services Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSliceDefault = prismic.SharedSliceVariation<
    'default',
    Record<string, never>,
    Simplify<ServicesSliceDefaultItem>
>

/**
 * Slice variation for *Services*
 */
type ServicesSliceVariation = ServicesSliceDefault

/**
 * Services Shared Slice
 *
 * - **API ID**: `services`
 * - **Description**: Services
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServicesSlice = prismic.SharedSlice<
    'services',
    ServicesSliceVariation
>

/**
 * Primary content in *GetInTouch → Primary*
 */
export interface TitleDescBtnSliceDefaultPrimary {
    /**
     * title field in *GetInTouch → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_desc_btn.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * desc field in *GetInTouch → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_desc_btn.primary.desc
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    desc: prismic.KeyTextField

    /**
     * buttonText field in *GetInTouch → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_desc_btn.primary.buttontext
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    buttontext: prismic.KeyTextField

    /**
     * buttonValue field in *GetInTouch → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_desc_btn.primary.buttonvalue
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    buttonvalue: prismic.KeyTextField
}

/**
 * Default variation for GetInTouch Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleDescBtnSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<TitleDescBtnSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *GetInTouch*
 */
type TitleDescBtnSliceVariation = TitleDescBtnSliceDefault

/**
 * GetInTouch Shared Slice
 *
 * - **API ID**: `title_desc_btn`
 * - **Description**: TitleDescBtn
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleDescBtnSlice = prismic.SharedSlice<
    'title_desc_btn',
    TitleDescBtnSliceVariation
>

/**
 * Primary content in *HomeHero → Primary*
 */
export interface TitleDescImgBtnSliceDefaultPrimary {
    /**
     * title field in *HomeHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_desc_img_btn.primary.title
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    title: prismic.KeyTextField

    /**
     * desc field in *HomeHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_desc_img_btn.primary.desc
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    desc: prismic.KeyTextField

    /**
     * img field in *HomeHero → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: title_desc_img_btn.primary.img
     * - **Documentation**: https://prismic.io/docs/field#image
     */
    img: prismic.ImageField<never>

    /**
     * buttonText field in *HomeHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_desc_img_btn.primary.buttontext
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    buttontext: prismic.KeyTextField

    /**
     * buttonValue field in *HomeHero → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_desc_img_btn.primary.buttonvalue
     * - **Documentation**: https://prismic.io/docs/field#key-text
     */
    buttonvalue: prismic.KeyTextField
}

/**
 * Default variation for HomeHero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleDescImgBtnSliceDefault = prismic.SharedSliceVariation<
    'default',
    Simplify<TitleDescImgBtnSliceDefaultPrimary>,
    never
>

/**
 * Slice variation for *HomeHero*
 */
type TitleDescImgBtnSliceVariation = TitleDescImgBtnSliceDefault

/**
 * HomeHero Shared Slice
 *
 * - **API ID**: `title_desc_img_btn`
 * - **Description**: TitleDescImgBtn
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleDescImgBtnSlice = prismic.SharedSlice<
    'title_desc_img_btn',
    TitleDescImgBtnSliceVariation
>

declare module '@prismicio/client' {
    interface CreateClient {
        (
            repositoryNameOrEndpoint: string,
            options?: prismic.ClientConfig
        ): prismic.Client<AllDocumentTypes>
    }

    namespace Content {
        export type {
            AboutDocument,
            AboutDocumentData,
            AboutDocumentDataSlicesSlice,
            ContactDocument,
            ContactDocumentData,
            ContactDocumentDataSlicesSlice,
            HomeDocument,
            HomeDocumentData,
            HomeDocumentDataSlicesSlice,
            LocDocument,
            LocDocumentData,
            LocDocumentDataSlicesSlice,
            NavigationDocument,
            NavigationDocumentData,
            NavigationDocumentDataSlicesSlice,
            ServicesDocument,
            ServicesDocumentData,
            ServicesDocumentDataSlicesSlice,
            AllDocumentTypes,
            AboutHeroSlice,
            AboutHeroSliceVariation,
            AboutHeroSliceDefault,
            AboutTalentSlice,
            AboutTalentSliceVariation,
            AboutTalentSliceDefault,
            ContactHeroSlice,
            ContactHeroSliceVariation,
            ContactHeroSliceDefault,
            LocItemSlice,
            LocItemSliceVariation,
            LocItemSliceDefault,
            LocationsSlice,
            LocationsSliceVariation,
            LocationsSliceDefault,
            PropertiesSlice,
            PropertiesSliceVariation,
            PropertiesSliceDefault,
            ServiceHeroSlice,
            ServiceHeroSliceVariation,
            ServiceHeroSliceDefault,
            ServiceProjectsSlice,
            ServiceProjectsSliceVariation,
            ServiceProjectsSliceDefault,
            ServicesSlice,
            ServicesSliceVariation,
            ServicesSliceDefault,
            TitleDescBtnSlice,
            TitleDescBtnSliceVariation,
            TitleDescBtnSliceDefault,
            TitleDescImgBtnSlice,
            TitleDescImgBtnSliceVariation,
            TitleDescImgBtnSliceDefault,
        }
    }
}
