// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from 'next/dynamic'

export const components = {
    about_hero: dynamic(() => import('./AboutHero')),
    about_talent: dynamic(() => import('./AboutTalent')),
    loc_item: dynamic(() => import('./LocItem')),
    locations: dynamic(() => import('./Locations')),
    properties: dynamic(() => import('./Properties')),
    service_hero: dynamic(() => import('./ServiceHero')),
    service_projects: dynamic(() => import('./ServiceProjects')),
    services: dynamic(() => import('./Services')),
    title_desc_btn: dynamic(() => import('./GetInTouch')),
    title_desc_img_btn: dynamic(() => import('./HomeHero')),
}
