import Header from '@/components/layout/header'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '@/components/layout/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className="bg-white">
                <Header />
                <div className="flex flex-col items-center justify-between pt-[120px] md:pt-[150px] min-h-screen">
                    <div className="max-w-[1300px] w-full">{children}</div>
                    <Footer />
                </div>
            </body>
        </html>
    )
}
